import Head from "next/head";
import React, { useState, useEffect } from "react";
import { useTransition, animated, config } from "react-spring";
import styles from "../styles/Home.module.css";

function Home() {
  const [index, set] = useState(0);
  useEffect(() => {
    void setInterval(() => set((state) => (state + 1) % 2), 5000);
  }, []);
  const slides = [
    {
      id: 0,
      url: "/tree.jpg",
    },
    {
      id: 1,
      url: "/tree2.jpg",
    },
  ];

  const transitions = useTransition(slides[index], (item) => item.id, {
    from: { opacity: 0 },
    enter: { opacity: 1 },
    leave: { opacity: 0 },
    config: config.molasses,
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>McCarver Freeman Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rat.svg" />
      </Head>

      <div className={styles.wrapper}>
        <div>
          {transitions.map(({ item, props, key }) => (
            <animated.div
              key={key}
              className={styles.photo}
              style={{
                ...props,
                backgroundImage: `url(${item.url})`,
              }}
            >
              <div className={styles.names}>
                <h3>Jared &</h3>
                <h3>Allyson</h3>
                <p>
                  We can't wait to share our special day with you. Help us
                  capture our wedding with Joy.
                </p>
              </div>
            </animated.div>
          ))}
        </div>
        <div className={styles.information}>
          <div className={styles.rsvp}>
            <h2>durham,</h2>
            <h2>north carolina</h2>
            <h3>Saturday, October 1, 2022</h3>
            <h3>227 Days 6 Hrs 9 Mins</h3>
            <button>rsvp</button>
            <p>View Details</p>
          </div>
          <div className={styles.border}></div>
        </div>
      </div>
    </div>
  );
}
export default Home;
